kind: pipeline
type: docker
name: integration

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk
    commands:
      - cd api
      - dotnet build


  #- name: test
  #  image: mcr.microsoft.com/dotnet/sdk
  #  environment:
  #    sqlconn:
  #      from_secret: sqlconn
  #  commands:
  #    - cd tests
  #    - dotnet test



  - name: code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    environment:
      SONARSECRET:
        from_secret: SonarQubeSecret
    commands:
      - dotnet sonarscanner begin
        /k:"easv-devops_TaskAppAA_AY85LDxgEVvRW2O60FJD"
        /d:sonar.host.url="http://sonar.setgo.dk:9000"
        /d:sonar.token="$SONARSECRET"
        /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
        /d:sonar.qualitygate.wait=true
      - dotnet build --no-incremental
      - dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
      - dotnet sonarscanner end /d:sonar.token="$SONARSECRET"
