services:
  task-app-frontend:
    image: aleksandramk/taskapp-web:prod
    
  task-app-backend:
    image: aleksandramk/taskapp-api:prod
  
  
  seq:
    image: datalust/seq
    ports:
      - 5341:5341
      - 5342:80
    volumes:
      - rps_seq_data:/data
    environment:
      - ACCEPT_EULA=Y  
        
  
volumes:
    rps_seq_data: 