services:
  task-app-frontend:
    image: aleksandramk/taskapp-web:latest
    ports:
      - "5001:4200"
    depends_on:
      - task-app-backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  
  task-app-backend:
    image: aleksandramk/taskapp-api:latest
    ports:
      - "5002:8080"
    environment:
      - sqlconn=Server=localhost;Database=task_app;Uid=myuser;Pwd=mypassword;
    depends_on:
      - mariadb
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task_app
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=mytoken
      - WATCHTOWER_LABEL_ENABLE=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8080:8080

volumes:
  mariadb: